import type { PublicMenuLocale } from '../types';
import type { PolecaneSlotId } from './dishRecommendations';

/** Opcje etykiety slotu napoju alkoholowego / wino w „Szef kuchni poleca”. */
export const POLECANE_BEVERAGE_SLOT_OPTIONS = [
  'Wino',
  'Whisky',
  'Piwo',
  'Koktail',
  'Wódka',
  'Sake',
  'Bourbon',
  'Koniak',
  'Brandy',
  'Tequila',
  'Likier',
  'Gin',
  'Rum',
] as const;

export type PolecaneBeverageSlotOption = (typeof POLECANE_BEVERAGE_SLOT_OPTIONS)[number];

export const DEFAULT_POLECANE_SLOT_LABELS: Record<PolecaneSlotId, string> = {
  'polecane-perfect-with': 'Wino',
  'polecane-finish-with': 'Deser',
  'polecane-add-a': 'Napój',
};

const LEGACY_BEVERAGE_LABELS = new Set(['Wino/piwo', 'Wine/Beer']);

export const POLECANE_SLOT_OPTION_I18N: Record<string, Record<PublicMenuLocale, string>> = {
  Wino: {
    pl: 'Wino',
    en: 'Wine',
    he: 'יין',
    ar: 'نبيذ',
    uk: 'Вино',
    de: 'Wein',
    es: 'Vino',
    it: 'Vino',
    ko: '와인',
    ja: 'ワイン',
    fr: 'Vin',
    cs: 'Víno',
    nl: 'Wijn',
    zh: '葡萄酒',
  },
  Whisky: {
    pl: 'Whisky',
    en: 'Whisky',
    he: 'וויסקי',
    ar: 'ويسكي',
    uk: 'Віскі',
    de: 'Whisky',
    es: 'Whisky',
    it: 'Whisky',
    ko: '위스키',
    ja: 'ウイスキー',
    fr: 'Whisky',
    cs: 'Whisky',
    nl: 'Whisky',
    zh: '威士忌',
  },
  Piwo: {
    pl: 'Piwo',
    en: 'Beer',
    he: 'בירה',
    ar: 'بيرة',
    uk: 'Пиво',
    de: 'Bier',
    es: 'Cerveza',
    it: 'Birra',
    ko: '맥주',
    ja: 'ビール',
    fr: 'Bière',
    cs: 'Pivo',
    nl: 'Bier',
    zh: '啤酒',
  },
  Koktail: {
    pl: 'Koktail',
    en: 'Cocktail',
    he: 'קוקטייל',
    ar: 'كوكتيل',
    uk: 'Коктейль',
    de: 'Cocktail',
    es: 'Cóctel',
    it: 'Cocktail',
    ko: '칵테일',
    ja: 'カクテル',
    fr: 'Cocktail',
    cs: 'Koktejl',
    nl: 'Cocktail',
    zh: '鸡尾酒',
  },
  Wódka: {
    pl: 'Wódka',
    en: 'Vodka',
    he: 'וודקה',
    ar: 'فودكا',
    uk: 'Горілка',
    de: 'Wodka',
    es: 'Vodka',
    it: 'Vodka',
    ko: '보드카',
    ja: 'ウォッカ',
    fr: 'Vodka',
    cs: 'Vodka',
    nl: 'Vodka',
    zh: '伏特加',
  },
  Sake: {
    pl: 'Sake',
    en: 'Sake',
    he: 'סאקה',
    ar: 'ساكي',
    uk: 'Саке',
    de: 'Sake',
    es: 'Sake',
    it: 'Sake',
    ko: '사케',
    ja: '日本酒',
    fr: 'Saké',
    cs: 'Sake',
    nl: 'Sake',
    zh: '清酒',
  },
  Bourbon: {
    pl: 'Bourbon',
    en: 'Bourbon',
    he: 'בורבון',
    ar: 'بوربون',
    uk: 'Бурбон',
    de: 'Bourbon',
    es: 'Bourbon',
    it: 'Bourbon',
    ko: '버번',
    ja: 'バーボン',
    fr: 'Bourbon',
    cs: 'Bourbon',
    nl: 'Bourbon',
    zh: '波本威士忌',
  },
  Koniak: {
    pl: 'Koniak',
    en: 'Cognac',
    he: 'קוניאק',
    ar: 'كونياك',
    uk: 'Коньяк',
    de: 'Kognak',
    es: 'Coñac',
    it: 'Cognac',
    ko: '코냑',
    ja: 'コニャック',
    fr: 'Cognac',
    cs: 'Koňak',
    nl: 'Cognac',
    zh: '干邑',
  },
  Brandy: {
    pl: 'Brandy',
    en: 'Brandy',
    he: 'ברנדי',
    ar: 'براندي',
    uk: 'Бренді',
    de: 'Brandy',
    es: 'Brandy',
    it: 'Brandy',
    ko: '브랜디',
    ja: 'ブランデー',
    fr: 'Brandy',
    cs: 'Brandy',
    nl: 'Brandy',
    zh: '白兰地',
  },
  Tequila: {
    pl: 'Tequila',
    en: 'Tequila',
    he: 'טקילה',
    ar: 'تيكيلا',
    uk: 'Текіла',
    de: 'Tequila',
    es: 'Tequila',
    it: 'Tequila',
    ko: '테킬라',
    ja: 'テキーラ',
    fr: 'Tequila',
    cs: 'Tequila',
    nl: 'Tequila',
    zh: '龙舌兰',
  },
  Likier: {
    pl: 'Likier',
    en: 'Liqueur',
    he: 'ליקר',
    ar: 'ليكور',
    uk: 'Лікер',
    de: 'Likör',
    es: 'Licor',
    it: 'Liquore',
    ko: '리큐르',
    ja: 'リキュール',
    fr: 'Liqueur',
    cs: 'Likér',
    nl: 'Likeur',
    zh: '利口酒',
  },
  Gin: {
    pl: 'Gin',
    en: 'Gin',
    he: "ג'ין",
    ar: 'جن',
    uk: 'Джин',
    de: 'Gin',
    es: 'Ginebra',
    it: 'Gin',
    ko: '진',
    ja: 'ジン',
    fr: 'Gin',
    cs: 'Gin',
    nl: 'Gin',
    zh: '金酒',
  },
  Rum: {
    pl: 'Rum',
    en: 'Rum',
    he: 'רום',
    ar: 'روم',
    uk: 'Ром',
    de: 'Rum',
    es: 'Ron',
    it: 'Rum',
    ko: '럼',
    ja: 'ラム',
    fr: 'Rhum',
    cs: 'Rum',
    nl: 'Rum',
    zh: '朗姆酒',
  },
  Deser: {
    pl: 'Deser',
    en: 'Dessert',
    he: 'קינוח',
    ar: 'حلوى',
    uk: 'Десерт',
    de: 'Dessert',
    es: 'Postre',
    it: 'Dolce',
    ko: '디저트',
    ja: 'デザート',
    fr: 'Dessert',
    cs: 'Dezert',
    nl: 'Dessert',
    zh: '甜点',
  },
  Napój: {
    pl: 'Napój',
    en: 'Beverage',
    he: 'משקה',
    ar: 'مشروب',
    uk: 'Напій',
    de: 'Getränk',
    es: 'Bebida',
    it: 'Bevanda',
    ko: '음료',
    ja: 'ドリンク',
    fr: 'Boisson',
    cs: 'Nápoj',
    nl: 'Drank',
    zh: '饮料',
  },
};

export function resolvePolecaneSlotLabel(slotId: PolecaneSlotId, raw?: string | null): string {
  const fallback = DEFAULT_POLECANE_SLOT_LABELS[slotId];
  const value = raw?.trim();
  if (!value || LEGACY_BEVERAGE_LABELS.has(value)) return fallback;
  if (slotId === 'polecane-perfect-with') {
    return (POLECANE_BEVERAGE_SLOT_OPTIONS as readonly string[]).includes(value) ? value : fallback;
  }
  return value;
}

export function getPolecaneSlotOptionLabel(label: string, locale: PublicMenuLocale): string {
  const tr = POLECANE_SLOT_OPTION_I18N[label];
  return tr?.[locale] || tr?.pl || label;
}

export function getPublicPolecaneSlotLabel(
  slotId: PolecaneSlotId,
  locale: PublicMenuLocale,
  customLabel?: string | null,
): string {
  const label = resolvePolecaneSlotLabel(slotId, customLabel);
  return getPolecaneSlotOptionLabel(label, locale);
}
